package com.syntevo.z8asm;

/**
 * @author Thomas Singer
 */
public enum TokenType {
	EOF, WHITESPACE, LINE_BREAK, COMMENT,
	INT_LITERAL,
	LABEL,
	AT, COMMA, HASH, L_PAREN, R_PAREN,
	WORK_REGISTER, WORK_REGISTER_PAIR, STRING, LENGTH_STRING,
	CONST, DATA, END, ORG, REPEAT,
	LD, LDE, LDC, LDEI, LDCI, CALL, DJNZ, JP, JR,
	DI, EI, RET, IRET, RCF, SCF, CCF, NOP,
	DEC, RLC, INC, SRP, DA, POP, COM, PUSH, DECW, RL, INCW, CLR, RRC, SRA, RR, SWAP,
	ADD, ADC, SUB, SBC, OR, AND, TCM, TM, CP, XOR,
	IDENTIFIER
}
